In [1]:
import numpy as np


In [2]:
arr= np.array([1,2,3,4])

In [3]:
arr

array([1, 2, 3, 4])

In [4]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [5]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [47]:
np.full((2,2),5)

array([[5, 5],
       [5, 5]])

In [52]:
import numpy as np

# Create 3x3 array with random numbers
arr = np.random.rand(3, 3)

# Print array
print(arr)

# Print shape
print(arr.shape)

[[0.48977851 0.38852069 0.5471547 ]
 [0.41044239 0.38620731 0.52019106]
 [0.49597375 0.45770179 0.35703755]]
(3, 3)


In [10]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [14]:
np.arange(0,20,5)

array([ 0,  5, 10, 15])

In [20]:
np.linspace(2,5,3)

array([2. , 3.5, 5. ])

In [24]:
myarr = np.array([[1,2,3],[4,5,6],[6,7,8],[11,12,13]])

In [25]:
myarr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 6,  7,  8],
       [11, 12, 13]])

In [29]:
print("shape:", myarr.shape)
print("size:", myarr.size)
print("dimension:", myarr.ndim)
print("data type:", myarr.dtype)

shape: (4, 3)
size: 12
dimension: 2
data type: int64


In [30]:
myarr = np.array([[1,2,3],[4,5,6],[6,7,8],[11,12,13]], dtype="float32")

In [31]:
myarr

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 6.,  7.,  8.],
       [11., 12., 13.]], dtype=float32)

In [34]:
n=myarr.astype("float64")

In [35]:
n.dtype

dtype('float64')

In [36]:
myarr.dtype

dtype('float32')

In [37]:
myarr = np.array([[1,2,3],[4,5,6],[6,7,8],[11,12,13]])

In [66]:
array4=np.random.rand(1,9)

In [68]:
array4.shape

(1, 9)

In [69]:
reshaped1=array4.reshape(3,3)

In [70]:
reshaped1

array([[0.91214921, 0.40796696, 0.12355909],
       [0.84933911, 0.97195194, 0.06517154],
       [0.44255717, 0.2826859 , 0.77960207]])

In [39]:
myarr.shape

(4, 3)

In [41]:
reshaped= myarr.reshape((3,4))

In [42]:
reshaped

array([[ 1,  2,  3,  4],
       [ 5,  6,  6,  7],
       [ 8, 11, 12, 13]])

In [43]:
myarr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 6,  7,  8],
       [11, 12, 13]])

In [44]:
myarr.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 6,  7,  8, 11, 12, 13]])

In [46]:
myarr.flatten()

array([ 1,  2,  3,  4,  5,  6,  6,  7,  8, 11, 12, 13])

In [62]:
array1=np.array([1.1, 2.2, 3.3],dtype="int")

In [63]:
array1.dtype

dtype('int64')

In [64]:
array1

array([1, 2, 3])

In [71]:
array5=np.array([33,55,66,22,88,55])
mask1=array5>50
print(array5[mask1])

[55 66 88 55]
