In [7]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6],[6,7,8],[11,12,13]])

In [8]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 6,  7,  8],
       [11, 12, 13]])

In [9]:
flat = arr.flatten()

In [10]:
flat

array([ 1,  2,  3,  4,  5,  6,  6,  7,  8, 11, 12, 13])

In [12]:
print(flat[0])

1


In [14]:
flat[3:6]

array([4, 5, 6])

In [15]:
flat[0:]

array([ 1,  2,  3,  4,  5,  6,  6,  7,  8, 11, 12, 13])

In [16]:
flat[:5]

array([1, 2, 3, 4, 5])

In [17]:
flat[3:]

array([ 4,  5,  6,  6,  7,  8, 11, 12, 13])

In [18]:
flat[3:13]

array([ 4,  5,  6,  6,  7,  8, 11, 12, 13])

In [20]:
print(flat[::2])

[ 1  3  5  6  8 12]


In [21]:
b=flat[4:7]

In [22]:
b

array([5, 6, 6])

In [23]:
b[0]=4444

In [24]:
b

array([4444,    6,    6])

In [26]:
flat

array([   1,    2,    3,    4, 4444,    6,    6,    7,    8,   11,   12,
         13])

In [27]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 6,  7,  8],
       [11, 12, 13]])

In [31]:
array1=np.array([1,2,3,4,5,6,6,733,22,55])
index=[1,5,7]
print(array1[index])

[  2   6 733]


In [32]:
array2=np.array([1,2,3,4,5,6,6,733,22,55])
mask=array2>25
print(array2[mask])

[733  55]


In [34]:
array3=np.array([1, 2, 3, 4, 5, 6])
index=[1,3,5]
print(array3[index])

[2 4 6]
