In [1]:
import numpy as np

In [20]:
array=np.array([1,33,5,46,4,4])

In [6]:
print(np.mean(array))

17.8


In [7]:
print(np.max(array))

46


In [8]:
print(np.min(array))

1


In [9]:
print(np.std(array))

18.23622768008779


In [10]:
print(np.var(array))

332.56000000000006


In [11]:
print(np.sum(array))

89


In [13]:
print(np.prod(array))

30360


In [14]:
print(np.median(array))

5.0


In [15]:
print(np.percentile(array,50))

5.0


In [18]:
print(np.argmin(array))

0


In [19]:
print(np.argmax(array))

3


In [21]:
print(np.unique(array))

[ 1  4  5 33 46]


In [22]:
print(np.diff(array))

[ 32 -28  41 -42   0]


In [23]:
print(np.cumsum(array))

[ 1 34 39 85 89 93]
