In [1]:
import numpy as np
array= np.array([[1,2,3],[4,5,6],[7,8,9]])

In [2]:
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
np.sum(array,axis=0)

array([12, 15, 18])

In [4]:
np.sum(array, axis=1)

array([ 6, 15, 24])

In [7]:
print(array[0:2,1:3])

[[2 3]
 [5 6]]


In [9]:
array3d=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[11,12,13]]])

In [10]:
print(array3d[0,1,2])

6


In [11]:
array3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [11, 12, 13]]])

In [12]:
print(array3d[:,0,:])

[[1 2 3]
 [7 8 9]]


In [21]:
firstcolumn=array3d[:,0]

In [22]:
print(firstcolumn)

[[1 2 3]
 [7 8 9]]


In [23]:
array3d[:,0,:]=0

In [24]:
array3d

array([[[ 0,  0,  0],
        [ 4,  5,  6]],

       [[ 0,  0,  0],
        [11, 12, 13]]])